name: word_maze
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this for internationalization
    sdk: flutter
  intl: 0.19.0 # Add this for internationalization
  provider: ^6.1.1 # Add this for state management
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  scratcher: ^2.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^4.0.2
  http: ^1.1.0  # Use the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true # Add this for i18n generation
  uses-material-design: true
  assets:
    - assets/images/boy_avatar.png
    - assets/images/girl_avatar.png
    - assets/images/Upload_photo.png
    - assets/images/guest_avatar.png
    - assets/images/wordmaze_logo.png
    - assets/images/app_icon.png
    - assets/sounds/click.mp3
    - assets/sounds/success.mp3
    - assets/sounds/fail.mp3
    - assets/words/en_words.json
    - assets/words/ar_words.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"